export enum ORDER_STATUS_ENUM {
  WAITING_PAYMENT = "WAITING_PAYMENT",
  PENDING = "WAITING_CONFIRMATION",
  REJECTED = "REJECTED",
  IN_PROGRESS = "IN_PROGRESS",
  ON_DELIVERY = "ON_DELIVERY",
  COMPLETED = "COMPLETED"
}