export const ENDPOINT = {
  SIGN_IN: () => `/auth/v1/sign-in`,
  SIGN_UP: () => `/auth/v1/sign-up`,
  LIST_PRODUCT: () => `/v1/product/list`,
  LIST_PRODUCT_ADMIN: () => `/v1/product/admin/list`,
  ARCHIVE_PRODUCT: (id: string) => `/v1/product/delete/${id}`,
  UPLOAD: () => `/v1/upload`,
  LIST_CATEGORY: () => `/v1/category/list`,
  CREATE_PRODUCT: () => `/v1/product/new`,
  EDIT_PRODUCT: (id: string) => `/v1/product/edit/${id}`,
  DETAIL_PRODUCT: (id: string) => `/v1/product/detail/${id}`,
  ADMIN_DETAIL_PRODUCT: (id: string) => `/v1/product/admin/detail/${id}`,
  COUNT_CART: () => `/chart/v1/count`,
  LIST_CART: () => `/chart/v1/list`,
  ADD_TO_CART: () => `/chart/v1/add`,
  REMOVE_CHART_ITEM: (id: string) => `/chart/v1/remove/${id}`,
  GET_DESTINATION: (q: string) => `/order/v1/destination?q=${q}`,
  CREATE_SHIPPING_ADDRESS: () => `/account/v1/create-shipping-address`,
  LIST_SHIPPING_ADDRESS: () => `/account/v1/shipping-address`,
  CHECK_DELIVERY_FEE: (code: string) => `/order/v1/check-delivery-fee?code=${code}`,
  CREATE_ORDER: () => `/order/v1/create`,
  LIST_ORDER_USER: () => `/order/v1/user/list`,
  DETAIL_ORDER: (id: string) => `/order/v1/detail/${id}`,
  UPLOAD_PAYMENT_IMAGE: (id: string) => `/order/v1/upload-payment-image/${id}`,
  GET_LIST_ORDER_ADMIN: () => `/order/v1/admin/list`,
  APPROVE_REJECT_ORDER: (id: string) => `/order/v1/admin/approve-reject/${id}`,
  INPUT_RESI: (id: string) => `/order/v1/admin/input-resi/${id}`,
  CONFIRM_ORDER: (id: string) => `/order/v1/user/confirm/${id}`,
  LIST_ACCOUNT: () => `/account/v1/list`,
  ORDER_REPORT: () => `/order/v1/admin/report`,
  CREATE_CATEGORY: () => `/v1/category/new`,
  EDIT_CATEGORY: () => `/v1/category/edit`,
  DELETE_CATEGORY: (id: string) => `/v1/category/delete/${id}`,
  CREATE_SUB_CATEGORY: () => `/v1/sub-category/new`,
  EDIT_SUB_CATEGORY: () => `/v1/sub-category/edit`,
  DELETE_SUB_CATEGORY: (id: string) => `/v1/sub-category/delete/${id}`,
};
