export const ENDPOINT = {
  SIGN_IN: () => `/auth/v1/sign-in`,
  SIGN_UP: () => `/auth/v1/sign-up`,
  LIST_PRODUCT: () => `/v1/product/list`,
  UPLOAD: () => `/v1/upload`,
  LIST_CATEGORY: () => `/v1/category/list`,
  CREATE_PRODUCT: () => `/v1/product/new`,
  DETAIL_PRODUCT: (id: string) => `/v1/product/detail/${id}`,
  COUNT_CART: () => `/chart/v1/count`,
  LIST_CART: () => `/chart/v1/list`,
  ADD_TO_CART: () => `/chart/v1/add`,
  REMOVE_CHART_ITEM: (id: string) => `/chart/v1/remove/${id}`,
  GET_DESTINATION: (q: string) => `/order/v1/destination?q=${q}`,
  CREATE_SHIPPING_ADDRESS: () => `/account/v1/create-shipping-address`,
  LIST_SHIPPING_ADDRESS: () => `/account/v1/shipping-address`,
  CHECK_DELIVERY_FEE: (code: string) => `/order/v1/check-delivery-fee?code=${code}`,
  CREATE_ORDER: () => `/order/v1/create`,
  LIST_ORDER_USER: () => `/order/v1/user/list`,
};
